# 워크플로우(작업) 이름
name: GitOps docker CICD Pipeline

# 1. 트리거 설정: 브랜치 정의
on:
  push:
    branches:
      - main

jobs:
  build-and-update:
    runs-on: ubuntu-latest # 실제 작업 주체
    
    # 작업 절차
    steps:
    - name: 소스코드 전송
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PASSWORD}}
    


    - name: AWS 자격 증명 설정
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
        aws-secret-access-key: ${{secrets.AWS_SECRETS_ACCESS_KEY}}
        aws-region: ${{secrets.AWS_REGION}}

    # ECR에 DOCKER 이미지 빌드 및 푸시
    # 이거는 git에서 시키는 ubuntu가 하는거야? ec2가 하는거야?
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2 

    - name: Build and push Docker image to ECR
      #  env:
      #   ECR_REGISTRY: ${{}}
      #   ECR_REPOSITORY: ${{}}
      #   IMAGE_TAG: ${{github.sha}}
      run: |
        docker build --no-cache -t 925047940866.dkr.ecr.ap-southeast-1.amazonaws.com/std07/nginx:1.31.3-ecr ./nginx
        docker build --no-cache -t 925047940866.dkr.ecr.ap-southeast-1.amazonaws.com/std07/nginx:latest ./nginx

        docker push 925047940866.dkr.ecr.ap-southeast-1.amazonaws.com/std07/nginx:1.31.3-ecr
        docker push 925047940866.dkr.ecr.ap-southeast-1.amazonaws.com/std07/nginx:latest

    - name: docker로 배포
      run: |
       aws ssm send-command \
        --instance-ids "i-04ded75b962b12fa9" \
        --document-name "AWS-RunShellScript" \
        --parameters "commands=[
          \"aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 925047940866.dkr.ecr.ap-southeast-1.amazonaws.com\",
          \"sudo docker pull 925047940866.dkr.ecr.ap-southeast-1.amazonaws.com/std07/nginx:latest\",
          \"sudo docker stop nginx-container || true\",
          \"sudo docker rm nginx-container\",
          \"sudo docker run -d --name nginx-container -p 80:80 925047940866.dkr.ecr.ap-southeast-1.amazonaws.com/std07/nginx:latest\"
        ]" \
        --region ${{secrets.AWS_REGION}} \
        --comment "Deploying SSM Docker"

